# Generated by Django 4.2.5 on 2023-09-21 15:35

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=6, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('E', 'Excellent'), ('G', 'Good'), ('A', 'Average'), ('P', 'Poor')], max_length=1)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.activity')),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.criteria')),
            ],
        ),
        migrations.CreateModel(
            name='NineBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nineboxes', to='api.class')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_aluno', models.BooleanField(default=False)),
                ('is_professor', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='student_profile', serialize=False, to='api.user')),
                ('classes', models.ManyToManyField(related_name='students', to='api.class')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='api.class')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='class_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.class'),
        ),
        migrations.AddField(
            model_name='activity',
            name='criteria',
            field=models.ManyToManyField(to='api.criteria'),
        ),
        migrations.AddField(
            model_name='activity',
            name='nine_boxes',
            field=models.ManyToManyField(to='api.ninebox'),
        ),
        migrations.AddField(
            model_name='activity',
            name='subjects',
            field=models.ManyToManyField(related_name='activities', to='api.subject'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='teacher_profile', serialize=False, to='api.user')),
                ('classes', models.ManyToManyField(related_name='teachers', to='api.class')),
            ],
        ),
        migrations.CreateModel(
            name='StudentNineBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('x', models.IntegerField(default=2)),
                ('y', models.IntegerField(default=1)),
                ('last_rank_fail_count', models.IntegerField(default=0)),
                ('nine_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ninebox')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('correction_date', models.DateField(blank=True, null=True)),
                ('final_grade', models.FloatField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_student_activities', to='api.activity')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_activity_class', to='api.class')),
                ('evaluations', models.ManyToManyField(related_name='student_activity_evaluations', to='api.evaluation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='nine_boxes',
            field=models.ManyToManyField(through='api.StudentNineBox', to='api.ninebox'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student'),
        ),
    ]
