# Generated by Django 4.2.5 on 2023-10-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_createsuperuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
