import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { UserProvider } from "../context/UserContext";
import Overlay from "./overlay";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "27Box",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          <Overlay />
          {children}
        </body>
      </UserProvider>
    </html>
  );
}
