# Generated by Django 4.2.5 on 2023-09-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_teacher',
            field=models.BooleanField(default=False),
        ),
    ]
