# Generated by Django 4.2.5 on 2023-09-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunoninebox',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alunoninebox',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
