# Generated by Django 4.2.5 on 2023-09-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_alunoninebox_x_alter_alunoninebox_y'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='criterio',
            name='nota',
        ),
    ]
