# Generated by Django 4.2.5 on 2023-09-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_evaluation_student_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentninebox',
            name='x',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentninebox',
            name='y',
            field=models.IntegerField(default=1),
        ),
    ]
