# Generated by Django 4.2.5 on 2023-09-20 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_studentninebox_x_alter_studentninebox_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentninebox',
            name='last_rank_fail_count',
            field=models.IntegerField(default=0),
        ),
    ]
