# Generated by Django 5.2.17 on 2026-09-19 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ninebox.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("role", models.CharField(choices=[("teacher", "Teacher"), ("student", "Student")], max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(default=ninebox.models.new_code, max_length=6, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("teacher", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="classes_taught", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name_plural": "classes",
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("due_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL)),
                (
                    "classroom",
                    models.ForeignKey(db_column="class_id", on_delete=django.db.models.deletion.CASCADE, related_name="activities", to="ninebox.class"),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Criterion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("description", models.CharField(max_length=140)),
                ("weight", models.PositiveSmallIntegerField(default=1)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="criteria", to="ninebox.activity")),
            ],
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("classroom", models.ForeignKey(db_column="class_id", on_delete=django.db.models.deletion.CASCADE, to="ninebox.class")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("student", "classroom")},
            },
        ),
        migrations.AddField(
            model_name="class",
            name="students",
            field=models.ManyToManyField(related_name="classes_joined", through="ninebox.Enrollment", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="Grid",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("classroom", models.ForeignKey(db_column="class_id", on_delete=django.db.models.deletion.CASCADE, related_name="grids", to="ninebox.class")),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="grids",
            field=models.ManyToManyField(related_name="activities", to="ninebox.grid"),
        ),
        migrations.CreateModel(
            name="Placement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("x", models.PositiveSmallIntegerField(default=2)),
                ("y", models.PositiveSmallIntegerField(default=1)),
                ("fail_streak", models.PositiveSmallIntegerField(default=0)),
                ("grid", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="placements", to="ninebox.grid")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="placements", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("student", "grid")},
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "classroom",
                    models.ForeignKey(db_column="class_id", on_delete=django.db.models.deletion.CASCADE, related_name="subjects", to="ninebox.class"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="activity",
            name="subjects",
            field=models.ManyToManyField(blank=True, related_name="activities", to="ninebox.subject"),
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("link", models.URLField(blank=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("final_grade", models.FloatField(blank=True, null=True)),
                ("activity", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to="ninebox.activity")),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="submissions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("activity", "student")},
            },
        ),
        migrations.CreateModel(
            name="PlacementHistory",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("level", models.PositiveSmallIntegerField()),
                ("x", models.PositiveSmallIntegerField()),
                ("y", models.PositiveSmallIntegerField()),
                ("grade", models.FloatField()),
                ("at", models.DateTimeField()),
                ("placement", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="history", to="ninebox.placement")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ninebox.submission")),
            ],
            options={
                "ordering": ["at"],
            },
        ),
        migrations.CreateModel(
            name="Mark",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("grade", models.CharField(choices=[("E", "Excellent"), ("G", "Good"), ("A", "Average"), ("P", "Poor")], max_length=1)),
                ("feedback", models.TextField(blank=True)),
                ("criterion", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="ninebox.criterion")),
                ("submission", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="marks", to="ninebox.submission")),
            ],
            options={
                "unique_together": {("submission", "criterion")},
            },
        ),
    ]
