# Generated by Django 5.2.17 on 2026-09-19 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ninebox", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placementhistory",
            name="label",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="placementhistory",
            name="submission",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ninebox.submission"),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("answers", models.JSONField(default=dict)),
                ("score", models.FloatField(blank=True, null=True)),
                ("student", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name="placementhistory",
            name="attempt",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="+", to="ninebox.attempt"),
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=140)),
                ("instructions", models.TextField(blank=True)),
                ("duration_minutes", models.PositiveSmallIntegerField(default=30)),
                ("level", models.PositiveSmallIntegerField(default=0)),
                ("status", models.CharField(choices=[("draft", "Draft"), ("open", "Open"), ("closed", "Closed")], default="draft", max_length=10)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("classroom", models.ForeignKey(db_column="class_id", on_delete=django.db.models.deletion.CASCADE, related_name="exams", to="ninebox.class")),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="+", to=settings.AUTH_USER_MODEL)),
                ("grids", models.ManyToManyField(related_name="exams", to="ninebox.grid")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="attempt",
            name="exam",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attempts", to="ninebox.exam"),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.TextField()),
                ("points", models.PositiveSmallIntegerField(default=1)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="ninebox.exam")),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("text", models.CharField(max_length=300)),
                ("is_correct", models.BooleanField(default=False)),
                ("question", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="choices", to="ninebox.question")),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="attempt",
            unique_together={("exam", "student")},
        ),
    ]
